### ISSUE TITLE
Error Popped Up

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [simbaja/milasdk#2]
An error started today...not sure why, still trying to figure it out. Seeing if anyone else is seeing it or know what might be up!
`Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/milasdk/api.py", line 62, in _execute
    return await session.execute(document, variable_values)
  File "/home/user/.local/lib/python3.9/site-packages/gql/client.py", line 1231, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': "Validation error (FieldUndefined@[owner/appliance/filter/daysLeft]) : Field 'daysLeft' in type 'ApplianceFilter' is undefined", 'locations': [{'line': 55, 'column': 9}], 'extensions': {'classification': 'ValidationError'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/mila-data.py", line 49, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user/mila-data.py", line 39, in main
    await update(api)
  File "/home/user/mila-data.py", line 19, in update
    a = await api.get_appliance(sys.argv[1])
  File "/home/user/.local/lib/python3.9/site-packages/milasdk/api.py", line 141, in get_appliance
    result = await self._execute(query)
  File "/home/user/.local/lib/python3.9/site-packages/milasdk/api.py", line 78, in _execute
    raise MilaError("Transport reported query error") from ex
milasdk.exceptions.MilaError: Transport reported query error`

**Comment by ReplicaObscura** [comment]
Maybe they removed or changed the daysLeft field somehow. I wonder what would happen if daysLeft were taken out of this SDK, if the rest would work or if it would start complaining about another field.

**Comment by disruptivepatternmaterial** [comment]
yanked out the filter and sensors from the q's and it works, so something changed in that schema...I just don't know how to tell what the gql is returning to remap the enums...

**Comment by disruptivepatternmaterial** [comment]
ok I removed filter and pressuremax from the gql and it is working again, no idea what to do next...but I'll keep poking.

**Comment by disruptivepatternmaterial** [comment]
ok so I went into the lib on my docker container and did the same thing and the plug in now works again, but much of the data is empty. if I can I will figure out the new gql map, but it is new to me...

**Comment by xagravel** [comment]
Adding a voice here as a witness to this issue. Have not been able to reproduce what @disruptivepatternmaterial was able to do on my end.

**Comment by disruptivepatternmaterial** [comment]
see #3 to fix it temporarily
